# Generated by Django 4.2.21 on 2025-05-26 15:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OutsourceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('nda_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outsource_requests', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OutsourceProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_percentage', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('outsource_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='progress', to='outsourceAPI.outsourcerequest')),
            ],
        ),
        migrations.CreateModel(
            name='OutsourceStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stage_type', models.CharField(choices=[('business_requirements', 'Business Requirements'), ('project_documentation', 'Project Documentation'), ('technical_questions', 'Technical Questions'), ('analysis', 'Analysis'), ('recommended_tech_stack', 'Recommended Tech Stack'), ('estimation', 'Estimation'), ('proposal', 'Proposal'), ('contract', 'Contract')], max_length=50)),
                ('document_link', models.URLField()),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('outsource_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stages', to='outsourceAPI.outsourcerequest')),
            ],
            options={
                'unique_together': {('outsource_request', 'stage_type')},
            },
        ),
    ]
