# Generated by Django 4.2.21 on 2025-05-18 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobBrief',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('brief_link', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='OutstaffCandidate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rate', models.DecimalField(decimal_places=2, max_digits=10)),
                ('role', models.CharField(max_length=100)),
                ('cv_link', models.URLField()),
                ('status', models.CharField(choices=[('not_available', 'Not Available'), ('available', 'Available'), ('interview', 'Interview'), ('test_task', 'Test Task'), ('approved', 'Approved')], default='available', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_brief', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='outstaffAPI.jobbrief')),
            ],
        ),
    ]
