# Generated by Django 4.2.21 on 2025-05-18 11:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('outstaffAPI', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='outstaffcandidate',
            name='job_brief',
        ),
    ]
